language: clojure

cache:
  directories:
  - $HOME/.m2

script:
  - lein checks
  - lein tests
  - lein doo once

after_success:
  - lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f target/coverage/codecov.json

notifications:
  Emlyn.Corrin@microsoft.com
